- name: "k3s common: iptables | allow related tcp ports"
  become: true
  ignore_errors: "{{ ansible_check_mode }}"
  ansible.builtin.iptables:
    action: insert
    chain: INPUT
    protocol: "{{ item.protocol }}"
    destination_ports: "{{ item.ports }}"
    jump: ACCEPT
  with_items:
    - protocol: tcp
      ports:
        - "2379:2380"
        - 6443
        - 10250
    - protocol: udp
      ports:
        - 8472
        - "51820:51821"

- name: "k3s common: iptables | save"
  become: true
  ignore_errors: "{{ ansible_check_mode }}"
  community.general.iptables_state:
    state: saved
    path: /etc/sysconfig/iptables
