- name: "k3s agent: install"
  ignore_errors: "{{ ansible_check_mode }}"
  ansible.builtin.shell:
    cmd: |
      curl -sfL https://get.k3s.io | K3S_NODE_NAME={{ k3s.agent.node.name }} K3S_URL=https://{{ k3s.server.node.ip_address }}:6443 K3S_TOKEN={{ k3s.token }} sh -s -
